# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - hexo
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "WaylandWong"
- git config --global user.email "TorWayland@gmail.com"
- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可
- npm install
script:
- hexo -v
- hexo clean
- hexo generate
- hexo d
after_success:
- ls 
- pip install beautifulsoup4
- pip install requests
- xcode-select --install
- pip install lxml
- python push.py

- cd ./public
- cp ../baidu_verify_24gDjcAcvq.html ./baidu_verify_24gDjcAcvq.html
- cp ../google466901c3bc99d1db.html .
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$REPO_TOKEN@github.com/WaylandWong/WaylandWong.github.io.git
  master
